version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/web/symfony

  php:
    image: php:7.2.5-fpm-alpine3.7
    ports:
      - 9000:9000
    volumes:
      - .:/web/symfony

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 9e2e4c4841810d4e1c74f8339b7398f0
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: ffcb137f9bf3bd5ec5beb5672126f31b
    volumes:
        - ./docker/mysql/var/lib/mysql:/var/lib/mysql

volumes:
  symfony:
